#!/bin/bash
rm -f $HOME/.config/fish/config.fish
mv $HOME/3b449/config.fish $HOME/.config/fish/

rm -f $HOME/.config/fish/functions/fish_prompt.fish
mv $HOME/3b449/fish_prompt.fish $HOME/.config/fish/functions/

rm -- "$0"