#!/bin/bash
rm -f $HOME/.config/fish/config.fish
mv $HOME/3b449/config.fish $HOME/.config/fish/

rm -f $HOME/.config/fish/functions/fish_prompt.fish
mv $HOME/3b449/fish_prompt.fish $HOME/.config/fish/functions/

rm -f $HOME/.config/fastfetch/config.jsonc
mv $HOME/3b449/config.jsonc $HOME/fastfetch/config.jsonc
rm -- "$0"
